package com.suba.Bankloanapplication.model;

public enum Permissions {
    GET_LOAN,
    APPROVE_LOAN,
    GET_LIST,
    SEND_MAIL, VISIT,
    APPROVE_DELETION, REQUEST_DELETION, GRANT_ADMIN_LOAN, VIEW_PENDING_DELETIONS,ASSIGN_ROLE, CREATE_ACCOUNT;


}
